sudo: false
language: node_js
node_js:
- '5.4.1'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: 363ee34e-cf09-4740-8802-9f67d71302ca
  app: code-rockr-app

after_script:
  - codecov
