sudo: false
language: node_js
node_js:
- '5.4.1'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules

after_script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: c069a093-19c7-42c6-84da-eeddb4a61d16
  app: code-rockr-app

after_script:
  - codecov
